# Generated by Django 4.1.7 on 2023-03-27 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_type', models.CharField(choices=[('zhk', 'ЖК'), ('zhsk', 'ЖСК')], max_length=4)),
                ('cooperative_name', models.CharField(max_length=255)),
                ('cooperative_itn', models.CharField(max_length=12)),
                ('cooperative_address', models.CharField(max_length=255)),
                ('cooperative_email_address', models.EmailField(max_length=254)),
                ('cooperative_telephone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('cooperative_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
