# Generated by Django 4.1.7 on 2023-03-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhk_meetings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='auditor_email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='auditor_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='chairman_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CooperativeQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('regular_only', models.BooleanField()),
                ('not_solvable_in_absentia', models.BooleanField()),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhk_meetings_app.cooperative')),
            ],
        ),
        migrations.CreateModel(
            name='CooperativeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhk_meetings_app.cooperative')),
            ],
        ),
    ]
