name: Deploy

on: [push]


jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host:  45.155.121.48
          username: zhk
          password: zhk_meetings
          script: |
            cd zhk_meetings
            git pull
            docker-compose down
            docker-compose up -d          
